// Try to maintain the json schema for easy maintanence.


const EventDetails = [
    {
        "event_name": "Building beyond land: An overview of coastal land reclamation in 16 global megacities",
        "year_Publish" : "2018",        
        "link": "https://www.sciencedirect.com/science/article/abs/pii/S0143622817305313",
    
        "event_description": "The increase in global population has been accompanied by rising consumption of natural resources such as clean air, water and land. Demand for land has increased significantly over the past 30 years or so, both inland and at the coast. In coastal regions, reclaiming land from the sea has often been the preferred solution towards meeting the need for more land for urban development. Seaward land reclamation entails the formation of artificial land surfaces which are constructed in such a way as to extend outwards over the sea using advanced geo-engineering techniques. The process is driven by numerous underlying factors and has manifold impacts. Although this pattern of urban development is not new, the nature, scale and magnitude of land extension has changed dramatically for a range of underlying reasons involving both ‘natural’ geophysical, and anthropogenic factors. The overall aim of this paper is to evaluate the changing spatial extent of seaward land expansion in 16 selected coastal megacities. Remote sensing data, spanning the time period mid-1980's to present, were obtained and used to determine the extent of spatial change due to new land construction in each of the cities. Landsat TM satellite imagery was used to calculate the percentage increase and area reclaimed since the mid-1980s. In addition, a systematic classification is proposed, based on the different geomorphic patterns that have been observed to characterize the process. Among 16 cities analyzed in this study, major land reclamation projects have been especially marked in China, most prominently in Shanghai, which has expanded its coastal area by more than 580 km2 in the recent past."
        
    
    },
    {
        "event_name": "Changing urban green spaces in Shanghai: trends, drivers and policy implications",
        "year_Publish" : "2019",        
        "link": "https://www.sciencedirect.com/science/article/abs/pii/S0264837719300651",
    
        "event_description": "Urban green spaces play a range of significant roles and have a positive influence on the quality of life in cities. Shanghai, a major economic and financial center in China, has set its goal to become a more ecologically integrated and livable city. The urban authorities envisage Shanghai as “a city in the forest, a forest in the city”. To achieve this greener future, the government has developed a series of policies to improve urban greening coverage. Based on land use and land cover data from 1980 to 2015, this paper analyzes temporal and spatial changes in urban green spaces in Shanghai, and explores the driving forces underlying the observed changes. Although the total urban green spaces in Shanghai declined from 1980 to 2015, different districts have different trends. Urban green spaces in the suburbs and the islands have declined, although, the city center increased its green spaces following several decades of decrease. Several factors have contributed to these changes, including population increase, conflicting government policies, real estate development, and rising demand for recreation space. Knowledge of the dynamics of urban green spaces in the city can assist in fostering an appropriate balance between urban development and environmental protection. To prevent environmental degradation and to plan a restoration pathway, cities should attempt to keep green spaces in mind during the development process and integrate the green spaces into urban planning. Understanding the dynamics of green spaces in Shanghai may offer insights for other cities in developing their own green spaces."
    
    },
    {
        "event_name": "Mapping Trajectories of Coastal Land Reclamation in Nine Deltaic Megacities using Google Earth Engine",
        "year_Publish" : "2019",        
        "link": "https://www.mdpi.com/2072-4292/11/22/2621",
    
        "event_description": "Increasing demand for land resources at the coast has exerted immense pressure on vulnerable environments. Population and economic growth in coastal cities have combined to produce a scarcity of suitable space for development, the response to which has frequently been the reclamation of land from the sea, most prominently in China. Urbanization is a key driver of such changes and a detailed investigation of coastal land reclamation at the city scale is required. This study analyzed remote sensing imagery for the period 1990 to 2018 to explore the trajectories of coastal land reclamation in nine major urban agglomerations across the three largest deltas in China using the JRC Global Surface Water (Yearly Water Classification History, v1.1) (GSW) dataset on the Google Earth Engine platform. The results are considered in the context of major national policy reforms over the last three decades. The analysis reveals that total land reclaimed among nine selected cities had exceeded 2800 km2 since 1984, 82% of which occurred after 2000, a year following the enactment of China’s agricultural ‘red line’ policy. Shanghai exhibited the greatest overall area of land extension, followed by Ningbo and Tianjin, especially in the period following the privatization of property rights in 2004. In analyzing annual trends, we identified the developmental stages of a typical coastal reclamation project and how these vary between cities. Scrutiny of the results revealed voids in nighttime light satellite data (2014–2018) in some localities. Although these voids appeared to be characterized by construction, they were occupied by vacant buildings, and were therefore examples of so-called “ghost cities.” In China, as elsewhere, continual land reclamation needs to be considered in relation to, inter alia, sea level rise and land subsidence that pose significant challenges to the vision of sustainable urban development in these three deltaic megacities"
    },
    {
        "event_name": "Gaining or losing ground? Tracking Asia's hunger for ‘new’ coastal land in the era of sea level rise",
        "year_Publish" : "2020",        
        "link": "https://www.sciencedirect.com/science/article/abs/pii/S0048969720328072",
    
        "event_description": "Many coastal cities are short of land for development and, coupled with the need to mitigate the impact of extreme events against a background of ongoing sea-level rise, coastal land reclamation (CLR) has emerged as a frequently applied solution, most especially in Asia. However, the sustainability of these newly reclaimed lands under the combined onslaught of increasing population pressure, SRL, greater frequency of extreme events, and land subsidence is largely unknown. In order to assess the spatial extent and temporal trends in recent CLR projects, we mapped and tabulated the annual magnitude of change in coastal land gain from 1988 to 2018 for eight major Asian coastal cities. Across these cities, both the spatial extent and rate of CLR is remarkable; some 700 km2 has been reclaimed in just three decades. >35% of this new coastal land has been constructed in Shanghai alone (562 km2), while Singapore and Incheon have also experienced substantial land gains. These three cities alone account for almost 10% of all the land gained globally over the last three decades. An analysis of the spatio-temporal patterns reveals that, since recently reclaimed areas are predominantly characterized by construction, including ports, airports, commercial and residential uses, economic development is the most prominent driver. Shanghai, however, represents a significant departure from this trend, whereby >50% of the new coastal land gained during the recent past has not been devoted to construction projects and is vegetated, suggesting a different policy context. Commercial or otherwise, subsidence is widely reported as a major characteristic of recently reclaimed coastal land and is a major environmental challenge. Mapping recent rates of land subsidence over these newly reclaimed lands reveal that most are subject to significant levels of deformation, in the case of the international airport at Incheon, Republic of Korea, exceeding 25 cm annually."
    },
    {
        "event_name": "An Analysis of Long-Term Rainfall Trends and Variability in the Uttarakhand Himalaya Using Google Earth Engine",
        "year_Publish" : "2020",        
        "link": "https://www.mdpi.com/2072-4292/12/4/709",
    
        "event_description": "This paper analyses the spatio-temporal trends and variability in annual, seasonal, and monthly rainfall with corresponding rainy days in Bhilangana river basin, Uttarakhand Himalaya, based on stations and two gridded products. Station-based monthly rainfall and rainy days data were obtained from the India Meteorological Department (IMD) for the period from 1983 to 2008 and applied, along with two daily rainfall gridded products to establish temporal changes and spatial associations in the study area. Due to the lack of more recent ground station rainfall measurements for the basin, gridded data were then used to establish monthly rainfall spatio-temporal trends for the period 2009 to 2018. The study shows all surface observatories in the catchment experienced an annual decreasing trend in rainfall over the 1983 to 2008 period, averaging 15.75 mm per decade. Analysis of at the monthly and seasonal trend showed reduced rainfall for August and during monsoon season as a whole (10.13 and 11.38 mm per decade, respectively); maximum changes were observed in both monsoon and winter months. Gridded rainfall data were obtained from the Climate Hazard Infrared Group Precipitation Station (CHIRPS) and Precipitation Estimation from Remotely Sensed Information Using Artificial Neural Networks-Climate Data Record (PERSIANN-CDR). By combining the big data analytical potential of Google Earth Engine (GEE), we compare spatial patterns and temporal trends in observational and modelled precipitation and demonstrate that remote sensing products can reliably be used in inaccessible areas where observational data are scarce and/or temporally incomplete. CHIRPS reanalysis data indicate that there are in fact three significantly distinct annual rainfall periods in the basin, viz. phase 1: 1983 to 1997 (relatively high annual rainfall); phase 2: 1998 to 2008 (drought); phase 3: 2009 to 2018 (return to relatively high annual rainfall again). By comparison, PERSIANN-CDR data show reduced annual and winter precipitation, but no significant changes during the monsoon and pre-monsoon seasons from 1983 to 2008. The major conclusions of this study are that rainfall modelled using CHIRPS corresponds well with the observational record in confirming the decreased annual and seasonal rainfall, averaging 10.9 and 7.9 mm per decade respectively between 1983 and 2008, although there is a trend (albeit not statistically significant) to higher rainfall after the marked dry period between 1998 and 2008. Long-term variability in rainfall in the Bhilangana river basin has had critical impacts on the environment arising from water scarcity in this mountainous region."
    },
    {
        "event_name": "“Whenever they say eco, they plant trees”: China’s flagship eco-cities as a model and the shades of eco-urbanism",
        "year_Publish" : "2020",        
        "link": "https://papersearch.net/thesis/article.asp?key=3850405",
    
        "event_description": "This paper critically interrogates the socioecological implications of China’s flagship eco-cities by conceptualizing them as a model that displays an idealized urban future in the assumed presence of an external audience. Examining two ongoing eco-city projects, the Sino-Singapore Tianjin Eco-City (SSTEC) and the Caofeidian International Eco-City (CIEC), we document how flagship eco-cities are discursively and materially manicured and how this aesthetically centered nature of a model exposes deep controversy of sustainability claims that these cities make. Combining qualitative and GIS research methods, we first demonstrate that the two cities are inherently growth-oriented and play a role of symbolic greening in the contexts of regional economic development. Second, we show that the flagship eco-cities create an unnecessarily high cost to fill the gap of the cities as idealized imaginary and as messy construction landscapes. Finally, in the particular cases of the SSTEC and the CIEC, “eco-” was interpreted as saving the country’s two most distressed resources: water and land. We argue that it led to accommodating the two cities in the already water-thirsty region, exacerbating the problem of groundwater depletion. Furthermore, we argue that, by choosing reclamation as a way of provisioning land, the two cities have brought devastating impacts to local communities and ecosystems, undermining social and ecological sustainabilities of the eco-city sites and surrounding areas. While existing literature on eco-urbanism tends to treat cities as a self-sustaining unit, we urge that there is a need to get out of the box: paying due attention to what an eco-city project does in the broader political-economic and ecological contexts."

    },
    {
        "event_name": "Global offshore wind turbine dataset",
        "year_Publish" : "2021",        
        "link": "https://www.nature.com/articles/s41597-021-00982-z",
    
        "event_description": "Offshore wind farms are widely adopted by coastal countries to obtain clean and green energy; their environmental impact has gained an increasing amount of attention. Although offshore wind farm datasets are commercially available via energy industries, records of the exact spatial distribution of individual wind turbines and their construction trajectories are rather incomplete, especially at the global level. Here, we construct a global remote sensing-based offshore wind turbine (OWT) database derived from Sentinel-1 synthetic aperture radar (SAR) time-series images from 2015 to 2019. We developed a percentile-based yearly SAR image collection reduction and autoadaptive threshold algorithm in the Google Earth Engine platform to identify the spatiotemporal distribution of global OWTs. By 2019, 6,924 wind turbines were constructed in 14 coastal nations. An algorithm performance analysis and validation were performed, and the extraction accuracies exceeded 99% using an independent validation dataset. This dataset could further our understanding of the environmental impact of OWTs and support effective marine spatial planning for sustainable development."
    
    },
    {
        "event_name": "Sources of sediment in tidal flats off Zhejiang coast, southeast China",
        "year_Publish" : "2021",        
        "link": "https://link.springer.com/article/10.1007/s00343-020-0179-2",
    
        "event_description": "The growth of tidal flats off Zhejiang coasts in southwestern China has provided substantial areas for local agriculture and construction activities. To evaluate modern and future development of tidal flats in the region, a good understanding of sediment sources is necessary. Previous research has concluded that the Changjiang (Yangtze) River is the dominant supplier of sediments to this part of the southeast Chinese coast, despite the fact that sediment delivery from this source has been decreased markedly in the past two decades. In this study, we investigated the sources of tidal flat sediments, and the magnetic and geochemical properties of recent tidal flat sediments along the Zhejiang coast were compared with those discharged from rivers. Magnetic and geochemical properties of the tidal flat samples reveal statistically distinct sediment provenance groups. The magnetic and geochemical scatter plots show that the suspended sediment samples are naturally divided into two different groups, one including the Changjiang River and Qiantang River material, and the other including the Jiaojiang, Oujiang, and Feiyun Rivers that located in the central and southern parts of the study areas. At last, a binary source of tidal flat sediments along the Zhejiang coast was determined, with the substantial majority originating from local rivers, while a much smaller proportion emanates from the Changjiang River to the north. We conclude that the sediment contribution of the Changjiang River to tidal flat development in the region has been markedly overestimated, with important implications for management."
    },
    {
        "event_name": "Tracking changes in aquaculture ponds on the China coast using 30 years of Landsat images",
        "year_Publish" : "2021",        
        "link": "https://www.sciencedirect.com/science/article/pii/S0303243421000908",
    
        "event_description": "Although coastal aquaculture ponds provide high-quality fish protein for billions of people, they are threatened by urbanization, pollution, and climate change. Moreover, colossal aquaculture ponds pose damages such as natural wetland shrinkage and water quality deterioration. However, understanding the trends and drivers of coastal aquaculture ponds on a national scale remains a challenge. In this study, a decision-tree classifier was used to quantify the spatiotemporal distribution of aquaculture ponds over last 30 years in 12 provinces located on the coast of China. Moreover, we analyzed their trends and drivers, including geographical conditions, socioeconomic factors, and development policies. The key results of the study include the following: (1) from 1990 to 2020, the cumulative area and holding area of aquaculture ponds reached 21997.90 km2 and 9613.66 km2, representing 3.7-fold and 1.6-fold increase, respectively, than the 1990 values. Based on geographical conditions, most aquaculture ponds tend to be located in coastal plains and bays following the distribution of low-lying land. (2) Influenced by different levels of socioeconomic development and changed policies, the holding area of aquaculture ponds experienced a “rapidly increasing period” from 1990 to 2011, growing by 246 km2 per year; “stable period” between 2011 and 2017; and “sharply shrinking period” after 2017 declining by 417 km2/year. (3) Coastal land reclamation played a critical role in the expansion of aquaculture ponds by cumulatively contributing approximately 22% of the land resource in the past 30 years. In the future, as a result of increasing land competition, the extent of aquaculture ponds on the China coast tends to decrease continually."
    }
]   

function viewEvent() {
    const eventSelect = document.getElementById("eventSelect").value;
    let count = 0;
    document.getElementById("eventContent").innerHTML =
        EventDetails.map((val) => {
            if (eventSelect == val.year_Publish) {
                count++;
                return (`<div class="col-sm-4 eachEvent">
            <h1 class="event_month">${val.year_Publish}</h1>
            <a href=${val.link}><h1  class="event_name">${val.event_name}</h1></a>         
            <p class="event_description">${val.event_description}</p>
        </div>`);
            }

        }).join("");
    if (count === 0) {
        document.getElementById("eventContent").innerHTML = `<p>No Publication Found For<u> ${eventSelect} </u>year</p>`
    }

}
